### ISSUE TITLE
fish animation

### ISSUE THREAD

**Issue by FxKu** [tudelft3d/Random3Dcity#4]
Trying out Random3Dcity for the first time to produce some CityGML for a training session. I run into an error caused by a missing package called fish. So is it missing then in your system requirements?

I've downloaded it from here https://pypi.python.org/pypi/fish and installed it, but it seems fish doesn't like my python. Got a syntax error (at 299 in fish.py: print fish_name).

Nevertheless I got everything working, After removing (commenting) all lines dealing with that package from generateCityGML.py :)

**Comment by fbiljecki** [comment]
Hi Felix,
Thanks for the report. I will add Fish as a system requirement in the readme next time I commit the changes. For the syntax error in fish.py: it's odd, I didn't run into this issue. Which version of Python are you running?

**Comment by FxKu** [comment]
I'm using Python 3.4.3 (32bit) on Win7 (64bit)

**Comment by fbiljecki** [comment]
I've updated the readme that the package Fish is required. I've tried to run the code with Python 3 and the latest version of Fish, but I can't reproduce the error. It seems to be a problem with the Fish package. Good that you've managed to run the code by uncommenting those a few lines.

**Comment by FxKu** [comment]
Ok. Thanks for checking. Actually it's a really cool tool to prepare test data sets for my LoD-Integrator plugin for the 3DCityDB, that I'm going to teach next week. I wonder why I haven't tried it before.

**Comment by fbiljecki** [comment]
Great, I am happy to hear that you had found it useful.
