### ISSUE TITLE
Caused SyntaxError: Missing parentheses in call to 'print' in Fish module

### ISSUE THREAD

**Issue by hgryoo** [tudelft3d/Random3Dcity#5]
Hello,
I tried to use this library and I faced the following error:
```
Traceback (most recent call last):
  File "generateCityGML.py", line 44, in <module>
    from fish import ProgressFish
  File "C:\Users\hyung\AppData\Local\Programs\Python\Python36-32\lib\site-packages\fish.py", line 299
    print fish_name
                  ^
SyntaxError: Missing parentheses in call to 'print'
```

I'm using python3 and windows 10.

The `print` statement in Python 3.x uses parenthesis:
```
print "Hello world"  # python 2.x
Is now

print("Hello world")   # python 3.x
```

I think the fish module is just used for reporting the progress of generating buildings.
After removing all lines that the Fish is used in generateCityGML.py, It is successfully worked without any reporting.. be patient :-p
(lines : 44, 4912, 4915, 5749, 5752)

For python3 users, I think an option to pass the lines that use fish module is needed.
(e.g. --python3)

Thank you for reading,
Hyung-Gyu

**Comment by fbiljecki** [comment]
Hi, many thanks for your contribution. I will keep it in mind for next time I update the code

**Comment by fbiljecki** [comment]
@hgryoo I have solved this issue. Thanks for reporting it.
I added a new option -rp for enabling/disabling reporting the progress of the generation of the datasets. This option is turned on by default. However, the option disables itself automatically if Fish cannot be loaded (which seems to be the case with Python3). I tested it with Python2 and 3, and it works with both.
