### ISSUE TITLE
Citation file

### ISSUE THREAD

**Issue by oew1v07** [tudelft3d/Random3Dcity#6]
Hi,

In your README you explain how to cite the project, which is brilliant. I thought I would suggest that you include a CITATION file (see [here](http://blog.rtwilson.com/encouraging-citation-of-software-introducing-citation-files/)) which allows for ease of citation when the repo has been cloned locally rather than having to find it within the README.

**Comment by fbiljecki** [comment]
Hi. Many thanks for the suggestion. I have now added a CITATION file.
