### ISSUE TITLE
Colors for buildings

### ISSUE THREAD

**Issue by unlugi** [tudelft3d/Random3Dcity#8]
Hello,

Thank you for this amazing repo.
How did you create the colors for the buildings? Like windows and roof etc?

**Comment by fbiljecki** [comment]
Thanks for your interest. The development of this project has ceased years ago, so I am afraid extensive support cannot be provided anymore. In brief, the colours have been set up in a 3D graphics software (Blender), which was used to visualise the data generated by this tool. Each type of semantic feature (e.g. window) has been obtained as a separate OBJ file, and a particular material (i.e. colour) has been set to each separately in Blender.
